/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/my/index" |
       "/pages/index/dibu" |
       "/pages/index/index" |
       "/pages/login/index" |
       "/pages/qrcode/index" |
       "/pages/shaicha/index" |
       "/pages/user-center/index" |
       "/pages/wendang/index" |
       "/pages/zixun/index" |
       "/pages-sub/changjianwenti/index" |
       "/pages-sub/danju/index" |
       "/pages-sub/demo/index" |
       "/pages-sub/fenleishezhi/index" |
       "/pages-sub/fuwuxieyi/index" |
       "/pages-sub/login/index" |
       "/pages-sub/quanbu-wendang-xuanze/index" |
       "/pages-sub/shaichajieguo/index" |
       "/pages-sub/shaichaxiangqing/index" |
       "/pages-sub/shougongshaicha/index" |
       "/pages-sub/shougongshaicha_xiangce/index" |
       "/pages-sub/shougongshaicha_xiangce_daoru/index" |
       "/pages-sub/user-center/user-info" |
       "/pages-sub/wuxiangchaxun/index" |
       "/pages-sub/yidong/index" |
       "/pages-sub/yidong2/index" |
       "/pages-sub/yijianfankui/index" |
       "/pages-sub/zixunxiangqing/index";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
